name: Docker CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rocq_version:
          - '9.0'
        ocaml_version:
          - '5.4-flambda'
      max-parallel: 4
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'rocq-ticl.opam'
          coq_version: ${{ matrix.rocq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          export: 'OPAMWITHTEST'
        env:
          OPAMWITHTEST: 'true'

