name: Docker CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rocq_version:
          - '9.1'
        ocaml_version:
          - '4.14-flambda'
      max-parallel: 4
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'rocq-ticl.opam'
          coq_version: ${{ matrix.rocq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          before_install: |
            startGroup "Upgrade dune"
              opam pin add dune 3.21.1 -y
            endGroup
            startGroup "Pin coinduction"
              opam pin add rocq-coinduction https://github.com/elefthei/coinduction.git -y
            endGroup
          export: 'OPAMWITHTEST'
        env:
          OPAMWITHTEST: 'true'

